# Generated by Django 5.1.6 on 2025-02-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.CharField(max_length=50, null=True, verbose_name='expertise'),
        ),
    ]
