# Generated by Django 5.1.6 on 2025-02-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expertise',
            field=models.CharField(blank=True, choices=[('dr', 'doctor'), ('sn', 'salon artist'), ('br', 'barber')], max_length=50, null=True, verbose_name='expertise'),
        ),
    ]
