# Generated by Django 5.1.6 on 2025-02-12 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(height_field=50, max_length=1, upload_to='services/', verbose_name='service image', width_field=50)),
                ('title', models.TextField(verbose_name='service title')),
                ('price', models.IntegerField(verbose_name='service price')),
                ('duration', models.IntegerField(verbose_name='service duration')),
                ('description', models.TextField(verbose_name='service description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
